### ISSUE TITLE
Windows watch error

### ISSUE THREAD

**Issue by cvd2412** [the-couch/slater#60] opened 2019-07-30 09:47 UTC
On Windows 10

![Udklip](https://user-images.githubusercontent.com/31840711/62119166-43f2e400-b2bf-11e9-8071-b1412168769e.PNG)

I can run the `slater build` command without issue, but when I run `slater watch` the above error shows up.

Could it be related to fsevents dependency not being installed? Any ideas on how to fix this issue?

**Comment by estrattonbailey** [comment] 2019-07-30 22:48
Duplicate of #11

**Closed by estrattonbailey** 2019-07-30 22:48 UTC
Labels: duplicate
